Repository coolstation/coolstation, pull requests merged in 2022-05, with the labels that each got.

#55 Murdering the sec vendor
  code/datums/jobs.dm
  code/obj/submachine/weapon_vendor.dm
Labels: size/M

#56 Adds wet wipes
  code/modules/medical/pathology/pathogen_machines.dm
  code/modules/vending/vending.dm
  code/obj/item/mops_cleaners.dm
  icons/obj/items/storage.dmi
  icons/obj/janitor.dmi
Labels: size/M

#58 Remove straggler access defines on airlocks
  code/obj/machinery/door/airlock.dm
  maps/cogmap.dmm
Labels: size/L

#59 Promouns
  _std/macros/mob_properties.dm
  _std/plane.dm
  browserassets/tgui/tgui.bundle.css
  browserassets/tgui/tgui.bundle.js
  code/datums/datacore.dm
  code/datums/preferences.dm
  code/datums/pronouns.dm
  code/datums/savefile.dm
  code/datums/viewport.dm
  code/mob.dm
  code/mob/dead/ai-camera.dm
  code/mob/dead/hivemind_observer.dm
  code/mob/dead/observer.dm
  code/mob/dead/target_observer.dm
  code/mob/input.dm
  code/mob/living/carbon/human.dm
  code/mob/living/carbon/human/monkeys.dm
  code/mob/living/carbon/human/procs/update_icon.dm
  code/mob/living/intangible/flock/flockmind.dm
  code/mob/living/silicon/ai.dm
  code/mob/living/silicon/robot.dm
  code/mob/wraith.dm
  code/modules/interface/name_tag.dm
  code/modules/medical/genetics/bioHolder.dm
  code/obj/decorations.dm
  code/procs/mob_procs.dm
  coolstation.dme
  icons/mob/human.dmi
  tgui/packages/tgui/interfaces/CharacterPreferences/GeneralTab.tsx
  tgui/packages/tgui/interfaces/CharacterPreferences/type.ts
Labels: size/XL

#60 Grey MPRT time
  icons/mob/back.dmi
  icons/mob/inhand/hand_weapons.dmi
  icons/obj/large/64x32.dmi
  icons/obj/projectiles.dmi
Labels: size/XS

#61 Spirit Station (WIP)
  _std/__build.dm
  _std/mapDefines.dm
  code/map.dm
  code/modules/worldgen/prefab/mapPrefab.dm
  code/obj/decal/corpsigns.dm
  code/obj/machinery/food_display.dm
  coolstation.dme
  icons/obj/decals/corpsigns.dmi
  icons/obj/machines/menudisplay.dmi
  maps/config/map.dm
  maps/config/spirit.dm
  maps/tamwip/spirit/spirit.dm
  maps/tamwip/spirit/spirit.dmm
  maps/tamwip/spirit/templates/foodhole/nanoburg.dmm
  maps/tamwip/spirit/templates/foodhole/notaburger.dmm
  maps/tamwip/spirit/templates/foodhole/warcys.dmm
Labels: size/XXL

#64 Adds admin button to tell off people for their gimmick
  browserassets/html/admin/berate_heavy.html
  browserassets/html/admin/berate_light.html
  code/modules/admin/admin.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/player_panel.dm
Labels: size/M

#66 CTRL-click allows releasing pulls
  code/WorkInProgress/hotkeys.dm
  code/mob/living.dm
Labels: size/XS
