Repository coolstation/coolstation, pull requests merged in 2022-07, with the labels that each got.

#98 fix some miscellaneous stuff
  code/mob/dead/observer.dm
  code/obj/item/device/radios/intercoms.dm
  code/obj/machinery/door/airlock.dm
  icons/obj/items/device.dmi
  maps/atlas.dmm
Labels: size/S

#96 Heavily reduce monkey fuck-around AI
  code/mob/living/carbon/human.dm
  code/mob/living/carbon/human/npc.dm
Labels: size/M

#72 Implements basics of cable switches
  code/modules/power/cable.dm
  code/modules/power/cable_switch.dm
  code/modules/power/power_parent.dm
  code/modules/vending/vending.dm
  coolstation.dme
  icons/obj/power.dmi
Labels: size/L

#108 deathgasp, it/its fixes
  code/datums/emotes/emote_complex.dm
  code/datums/pronouns.dm
Labels: size/XS

#113 Dialogs and Such
  browserassets/html/motd.html
  browserassets/html/traitorTips/antagRemoved.html
  browserassets/html/traitorTips/football.html
  browserassets/html/traitorTips/kudzu.html
  browserassets/html/traitorTips/syndiTips.html
  browserassets/html/traitorTips/traitorTips.html
  browserassets/html/traitorTips/traitorsleeperTips.html
  browserassets/html/traitorTips/vampireTips.html
  browserassets/html/traitorTips/vampiricthrallTips.html
  browserassets/html/traitorTips/werewolfTips.html
  browserassets/images/motd/aibo.gif
  browserassets/images/motd/lightsaber.gif
Labels: size/M
