Repository coolstation/coolstation, pull requests merged in 2022-12, with the labels that each got.

#119 Add message groups to a bunch of things
  code/modules/chemistry/tools/dispensers.dm
  code/modules/power/lighting.dm
  code/modules/transport/pods/ships.dm
  code/obj/bookcase.dm
  code/obj/displaycase.dm
  code/obj/item/rcd.dm
  code/obj/railing.dm
  code/obj/table.dm
  code/turf/walls.dm
Labels: size/L, juicy

#128 Add AI support to gehenna Z3, more or less
  _std/mapDefines.dm
  code/mob/dead/ai-camera.dm
  code/mob/living/silicon/ai.dm
  code/mob/living/silicon/ai/camera_handling.dm
  code/z_adventurezones/lavamoon.dm
Labels: size/M

#129 kudzoolander
  _std/__build.dm
  code/datums/controllers/process/kudzu.dm
  code/datums/mutantraces.dm
  code/modules/_unused/kudzumen.dm
  code/modules/admin/admin.dm
  code/modules/events/gimmick/kudzu.dm
  code/modules/interface/multiContext/context_actions.dm
  code/obj/critter/plants.dm
  code/obj/item/seeds.dm
  code/obj/machinery/computer/cloning.dm
  code/obj/machinery/plantpot.dm
  code/obj/submachine/seed.dm
  code/procs/fireflash.dm
  code/procs/mobprocs/chatprocs.dm
  coolstation.dme
Labels: size/L

#130 Ritos-italian-ice
  assets/maps/random_rooms/5x4/mall_ritos.dmm
  code/modules/chemistry/Chemistry-Holder.dm
  code/modules/food_and_drink/ice_cream.dm
  code/obj/decal/poster.dm
  code/obj/submachine/cooking.dm
  icons/obj/decals/wallsigns.dmi
  icons/obj/foodNdrink/food_snacks.dmi
Labels: size/L

#131 Spawnable-fruits
  code/modules/food_and_drink/plants.dm
  code/obj/item/storage/food.dm
Labels: size/M

#132 ritos prefab now uses the new spawnable fruits
  assets/maps/random_rooms/5x4/mall_ritos.dmm
Labels: size/XS

#134 Adds cave generation for Gehenna Colony
  _std/defines/worldgen.dm
  assets/maps/prefabs/prefab_cave_bread.dmm
  assets/maps/prefabs/prefab_cave_long.dmm
  assets/maps/prefabs/prefab_cave_meat.dmm
  assets/maps/prefabs/prefab_cave_spider.dmm
  assets/maps/prefabs/prefab_cave_wide.dmm
  code/modules/worldgen/GenerateMining.dm
  code/modules/worldgen/prefabs.dm
  code/obj/mining.dm
  code/world.dm
  maps/warwip/gehenna_colony.dmm
  maps/warwip/z3_gehenna.dmm
  strings/changelog.txt
Labels: size/XXL

#135 Mining map support for gehenna Z3
  code/datums/controllers/sea_hotspot_controls.dm
  code/modules/worldgen/GenerateMining.dm
  code/obj/item/device/pda2/base_os.dm
  code/turf/floors.dm
Labels: size/L
