Repository coolstation/coolstation, pull requests merged in 2022-04, with the labels that each got.

#40 no hub round data in dev
  code/procs/export_data.dm
Labels: size/XS

#39 Raking it in
  code/datums/syndicate_buylist.dm
  code/obj/machinery/plantpot.dm
  icons/obj/hydroponics/machines_hydroponics.dmi
Labels: size/M

#42 Minor map alterations over compile issues
  maps/cogmap.dmm
  maps/donut3.dmm
Labels: size/S

#41 infinite corpse piss glass bug fixed
  code/modules/chemistry/tools/food_and_drink.dm
Labels: size/S

#46 Cables but without ruining the history this time?
  code/mob/living/silicon/drone.dm
  code/modules/power/cable.dm
  code/obj/item/cable_coil.dm
  code/turf/floors.dm
Labels: size/L

#48 Face unmelting
  code/mob.dm
  code/mob/dead/observer.dm
  code/modules/antagonists/changeling/abilities/transform.dm
  code/modules/chemistry/Reagents-Medical.dm
  code/modules/chemistry/Reagents-PoisonEtc.dm
Labels: size/M

#50 Goshhecking light switches debug overlay
  code/modules/admin/diagnostics.dm
  strings/admin_changelog.txt
Labels: size/M

#53 Bugfixes (cable coils, borg mesons)
  code/mob/living/life/sight.dm
  code/obj/item/cable_coil.dm
Labels: size/XS

#52 the butt store called
  assets/maps/random_rooms/3x5/buttstore.dmm
Labels: size/L, stale

#54 Allow for tank storage crime
  code/obj/machinery/dispenser.dm
Labels: size/L
