Repository coolstation/coolstation, pull requests merged in 2022-06, with the labels that each got.

#67 Mall cop-ification part 2
  code/datums/jobs.dm
  code/datums/supply_packs.dm
  code/obj/item/clothing/armor.dm
  code/obj/item/device/pda2/pda2.dm
  code/obj/storage/secure_closets.dm
Labels: size/S

#69 Poo text variety
  code/mob/living/carbon.dm
Labels: size/XS

#70 making quivering contusine cool
  code/modules/hydroponics/plant_mutations.dm
Labels: size/XS

#74 Razorwave
  code/modules/loafstation/razorwave.dm
  code/modules/sound/soundCache.dm
  code/obj/storage/secure_closets.dm
  coolstation.dme
  icons/loafstation/razorwave.dmi
  sound/machines/razorwave_scan.ogg
  sound/machines/razorwave_scour.ogg
Labels: size/L

#79 sprites for overhead fluorescent lights
  icons/obj/lighting.dmi
Labels: size/XS

#82 normalized + added two new songs for oldsax
  code/obj/item/instruments.dm
  sound/musical_instruments/sax/sax8.ogg
  sound/musical_instruments/sax/sax9.ogg
Labels: size/XS

#80 Autothindows and misc stuff
  code/datums/abilities/wizard/pandemonium.dm
  code/obj/grille.dm
  code/obj/window.dm
  code/turf/turf.dm
  icons/obj/window.dmi
Labels: size/L

#77 fix monkey heads
  code/datums/mutantraces.dm
Labels: size/XS

#84 this too
  code/modules/admin/admin.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/create.dm
Labels: size/M

#78 Pine Marten
  code/mob/living/carbon/human/procs/emote.dm
  code/mob/living/critter/small_animal.dm
  icons/misc/critter.dmi
Labels: size/M

#81 Lighting handling, ceiling fluorescent lights
  code/modules/power/lighting.dm
Labels: size/M

#85 :frogout:
  _std/macros/appearance.dm
  code/WorkInProgress/pali.dm
  code/WorkInProgress/rewardsLocker.dm
  code/WorkInProgress/tarmStuff.dm
  code/datums/components/barber.dm
  code/datums/mutantraces.dm
  code/modules/admin/spacebee_extension/commands.dm
  code/modules/chemistry/Reagents-Diseases.dm
  code/modules/items/gimmick/figurine.dm
  code/modules/vending/vending.dm
  code/obj/item/book.dm
  code/obj/item/cigarette.dm
  code/obj/item/mob_parts/human_parts.dm
  code/obj/item/organs/head.dm
  code/obj/machinery/printing_press.dm
  code/procs/mobprocs/chatprocs.dm
  strings/books/fun_facts_about_shelterfrogs.txt
Labels: size/L

#87 Classic Toolset (Items/Devices)
  icons/obj/items/device.dmi
  icons/obj/items/items.dmi
  icons/obj/items/tools/crowbar.dmi
  icons/obj/items/tools/multitool.dmi
  icons/obj/items/tools/screwdriver.dmi
  icons/obj/items/tools/weldingtool.dmi
  icons/obj/items/tools/wirecutters.dmi
  icons/obj/items/tools/wrench.dmi
Labels: size/XS

#76 Modernizes Space Rhinovirus
  code/datums/disease.dm
  code/modules/medical/diseases/dna_spread.dm
Labels: size/M

#88 Datumised human emotes, quality not guaranteed
  _std/defines/mob.dm
  _std/macros/mob_status.dm
  code/datums/emotes/emote_complex.dm
  code/datums/emotes/emote_huge.dm
  code/datums/emotes/emote_monologue.dm
  code/datums/emotes/emote_parent.dm
  code/datums/emotes/emote_simple.dm
  code/datums/emotes/emote_targeted.dm
  code/mob/living/carbon/human/procs/emote.dm
  code/mob/living/critter/small_animal.dm
  code/world.dm
  coolstation.dme
Labels: size/XXL

#90 im coder
  code/modules/admin/admin_verbs.dm
Labels: size/XS

#86 Babmop
  code/WorkInProgress/bobskunk.dm
  code/map.dm
  code/mob/living/critter/small_animal.dm
  maps/bobmap.dmm
Labels: size/XXL

#93 Adds a mostly placeholder credits tab
  code/credits.dm
  coolstation.dme
  interface/skin.dmf
Labels: size/S
