Repository coolstation/coolstation, pull requests merged in 2023-02, with the labels that each got.

#151 Clarify freezer buttons
  browserassets/tgui/tgui.bundle.js
  tgui/packages/tgui/interfaces/Freezer.tsx
Labels: size/XS

#152 Some emote fixes
  code/datums/emotes/emote_complex.dm
  code/datums/emotes/emote_parent.dm
  code/datums/emotes/emote_simple.dm
  code/mob/living/carbon/human/procs/emote.dm
Labels: size/L

#153 fish revamp
  code/datums/jobs.dm
  code/modules/admin/admin_verbs.dm
  code/modules/fishing/fishing_gear.dm
  code/modules/fishing/fishing_spots.dm
  code/modules/vending/vending.dm
  code/obj/machinery/deep_fryer.dm
Labels: size/L

#156 this fucking FEA helper
  code/modules/atmospherics/FEA_group_helpers.dm
Labels: size/XS

#157 Ports 10807
  code/atom.dm
  code/atom/UpdateOverlays.dm
  code/datums/tooltip.dm
  code/mob/living/critter/flock/flockdrone.dm
  code/mob/living/critter/flockcritter_parent.dm
  code/mob/living/critter/small_animal.dm
  code/modules/admin/atom_verbs.dm
  code/modules/chemistry/Reagents-Base.dm
  code/modules/chemistry/Reagents-FoodDrink.dm
  code/modules/chemistry/Reagents-Misc.dm
  code/modules/events/supply_drop.dm
  code/modules/food_and_drink/snacks.dm
  code/modules/items/gimmick/figurine.dm
  code/modules/materials/Mat_ProcsDefines.dm
  code/modules/medical/genetics/bioEffects/powers.dm
  code/modules/mining/ore.dm
  code/modules/power/cable.dm
  code/obj/flock/furniture.dm
  code/obj/item/handcuffs.dm
  code/obj/item/material.dm
  code/obj/table.dm
  code/obj/window.dm
  code/turf/floors.dm
  code/turf/floors_airless.dm
  code/turf/floors_unsimulated.dm
  code/turf/turf_autoalign.dm
  code/turf/turf_flock.dm
  code/turf/walls.dm
Labels: size/L

#158 Maybe a small ReplaceWith optimisation?
  code/turf/floors.dm
  code/turf/turf.dm
Labels: size/S

#159 (mostly) removes the need for copying materials
  _std/defines/atom.dm
  _std/defines/materials.dm
  code/atom.dm
  code/modules/materials/Mat_FabRecipes.dm
  code/modules/materials/Mat_MaterialProcs.dm
  code/modules/materials/Mat_Materials.dm
  code/modules/materials/Mat_Processing.dm
  code/modules/materials/Mat_ProcsDefines.dm
  code/modules/materials/Mat_Properties.dm
  code/modules/power/cable.dm
  code/modules/power/rtg.dm
  code/obj/displaycase.dm
  maps/warwip/gehenna_colony.dmm
Labels: size/L

#160 Big Italian Shoe
  code/obj/vehicle.dm
  icons/obj/vehicles.dmi
Labels: size/M

#162 does this work
  icons/obj/items/modular_guns/accessory.dmi
  icons/obj/items/modular_guns/sovgun.dmi
Labels: size/XS

#163 Things and stuff
  icons/mob/back.dmi
  icons/mob/head.dmi
  icons/mob/lizard_clothes.dmi
  icons/mob/overcoats/worn_suit_hazard.dmi
  icons/obj/clothing/item_hats.dmi
  icons/obj/clothing/overcoats/item_suit_hazard.dmi
  icons/obj/items/modular_guns/grips.dmi
  icons/obj/items/modular_guns/old_taser_parts.dmi
  icons/obj/items/modular_guns/stocks.dmi
  icons/obj/items/storage.dmi
Labels: size/XS

#164 Packing machine resprite
  code/obj/machinery/launcherloader.dm
  icons/obj/recycling.dmi
Labels: size/XS

#167 Blob Level Transfer
  code/modules/antagonists/blob/blob_abilities.dm
  code/modules/shuttles/elevators.dm
  code/modules/shuttles/transit_vehicle.dm
  code/obj/blob.dm
  code/z_adventurezones/lavamoon.dm
  icons/mob/blob_organs.dmi
  icons/mob/blob_ui.dmi
Labels: size/L
