Repository coolstation/coolstation, pull requests merged in 2023-08, with the labels that each got.

#190 Screaming Tuna Pillow
  code/obj/item/fitness.dm
  icons/obj/plushies.dmi
  sound/effects/ohmygodtuna.ogg
Labels: size/M

#185 Phonecord but fixed
  code/obj/machinery/phone.dm
  icons/obj/machines/phones.dmi
Labels: size/M

#191 Folding bins
  code/obj/item/table_rack_parts.dm
  code/obj/table.dm
  icons/obj/scrap.dmi
Labels: size/S

#192 Adds Big Challenges and plants/rock decoration to gehenna's surface
  code/obj/decal.dm
  code/obj/decal/cleanable.dm
  code/obj/decal/poster.dm
  icons/obj/decals/graffiti.dmi
  icons/obj/decoration.dmi
  maps/warwip/gehenna_colony.dmm
  maps/warwip/z3_gehenna.dmm
Labels: merge conflict, size/XXL

#194 Ghostfactory
  maps/warwip/z3_gehenna.dmm
Labels: size/XXL

#201 Clothing Sprite Fix
  icons/mob/back.dmi
  icons/mob/ears.dmi
  icons/mob/head.dmi
  icons/obj/clothing/item_hats.dmi
Labels: size/XS

#205 ghoist teleport to shouttle
  code/datums/abilities/ghost_observer.dm
  code/datums/abilities/shared_ghost.dm
  icons/mob/ghost_observer_abilities.dmi
Labels: size/M
