Repository coolstation/coolstation, pull requests merged in 2023-05, with the labels that each got.

#179 Intercom style apc map icon
  code/modules/power/apc.dm
  icons/obj/power.dmi
Labels: size/XS

#180 Neon lining autoplace
  code/obj/item/neon_lining.dm
  code/obj/neon_lining.dm
  icons/obj/decals/neon_lining.dmi
Labels: size/L

#177 experimental: AI governors
  _std/defines/ai.dm
  code/datums/viewport.dm
  code/mob/living.dm
  code/modules/networks/computer3/modular_ai_machines.dm
  code/modules/power/apc.dm
  code/obj/item/device/pda2/cartridges.dm
  code/obj/item/device/pda2/smallprogs.dm
  code/obj/machinery/door/airlock.dm
  coolstation.dme
  icons/obj/networked.dmi
Labels: size/L, juicy
