Repository coolstation/coolstation, pull requests merged in 2023-01, with the labels that each got.

#136 Mud overlays
  code/mob/living/carbon/human.dm
  code/mob/living/carbon/human/procs/update_icon.dm
  code/modules/forensics/atom_forensic.dm
  icons/misc/not_poo.dmi
Labels: size/L

#137 Autohacker traitor item
  code/datums/syndicate_buylist.dm
  code/obj/item/device/hacking_laptop.dm
  coolstation.dme
  icons/mob/inhand/hand_general.dmi
  icons/obj/computer.dmi
Labels: size/L

#140 Loose tiles
  code/obj/decal.dm
  code/obj/item/building_materials.dm
  code/turf/floors.dm
Labels: size/M

#143 Fixes for buildable atmos 1
  _std/macros/dir.dm
  code/modules/atmospherics/atmos_crafting.dm
  code/modules/atmospherics/machinery/unary/freezer.dm
  code/modules/power/TEG.dm
  code/obj/item/building_materials.dm
Labels: size/L

#144 atmos crafting fixbatch 2
  code/modules/atmospherics/atmos_crafting.dm
  code/modules/atmospherics/machinery/mixer.dm
  code/modules/atmospherics/machinery/pipe.dm
  code/modules/atmospherics/machinery/unary/freezer.dm
  icons/obj/atmospherics/pipes/manifold_pipe.dmi
Labels: size/L

#145 pronoun replacements
  code/WorkInProgress/HaineWhatever.dm
  code/datums/components/barber.dm
  code/datums/gamemodes/gm_parent.dm
  code/datums/limb.dm
  code/mob/living/carbon/human/monkeys.dm
  code/mob/living/critter/aquatic.dm
  code/modules/admin/randomverbs.dm
  code/obj/item/cameras.dm
  code/obj/item/device/voltron.dm
  code/obj/item/gift.dm
  code/obj/item/grab.dm
  code/obj/item/implant.dm
  code/obj/item/misc_weapons.dm
  code/obj/item/mob_parts/human_parts.dm
  code/obj/item/uplinks.dm
  code/obj/machinery/singularity.dm
  code/obj/misc_junk.dm
  code/obj/portal.dm
  code/obj/stool.dm
  code/procs/mob_procs.dm
Labels: size/L

#146 wierd sprites
  icons/mob/lizard_clothes.dmi
  icons/obj/syringe.dmi
Labels: size/XS

#147 Add elevator buttons
  _std/defines/component_defines.dm
  code/modules/shuttles/elevators.dm
  code/modules/shuttles/transit_vehicle.dm
  icons/obj/machines/buttons.dmi
Labels: size/L

#148 Ports the freezer TGUI from Goonstation
  browserassets/tgui/tgui-common.bundle.js
  browserassets/tgui/tgui-panel.bundle.js
  browserassets/tgui/tgui.bundle.css
  browserassets/tgui/tgui.bundle.js
  code/modules/atmospherics/machinery/unary/freezer.dm
  tgui/packages/tgui/interfaces/Freezer.tsx
  tgui/packages/tgui/interfaces/common/temperatureUtils.js
Labels: size/L
