Repository coolstation/coolstation, pull requests merged in 2023-03, with the labels that each got.

#169 Gehenna blowout variant
  code/modules/events/blowout.dm
  code/modules/events/blowout_gehenna.dm
  coolstation.dme
Labels: size/L

#172 Industrial Combat Armor
  code/datums/manufacturing.dm
  code/obj/item/clothing/helmets.dm
  code/obj/item/clothing/suits.dm
  code/obj/machinery/manufacturer.dm
Labels: size/S

#173 Merge surgery tray/kitchen island into tables
  assets/maps/prefabs/prefab_outpost.dmm
  assets/maps/prefabs/prefab_von_ricken.dmm
  assets/maps/random_rooms/5x3/operatingroom_75.dmm
  code/modules/medical/surgery_tools.dm
  code/modules/vending/vending.dm
  code/obj/item/kitchen.dm
  code/obj/table.dm
  maps/atlas.dmm
  maps/atlas_xmas_2020.dmm
  maps/bobwip/bobmap.dmm
  maps/bobwip/dockmap.dmm
  maps/cogmap.dmm
  maps/cogmap2.dmm
  maps/cogmap2_xmas_2020.dmm
  maps/cogwip/ships.dmm
  maps/cogwip/ships_1.dmm
  maps/destiny.dmm
  maps/donut3.dmm
  maps/donut3_xmas.dmm
  maps/horizon.dmm
  maps/horizon_xmas.dmm
  maps/kondaru.dmm
  maps/manta.dmm
  maps/manta_damaged.dmm
  maps/oshan.dmm
  maps/oshan_xmas.dmm
  maps/ozymandias.dmm
  maps/pamgoc.dmm
  maps/pod_wars.dmm
  maps/setpieces/AZUN_azarak.dmm
  maps/setpieces/MARQ_terra8.dmm
  maps/tamwip/spirit/spirit.dmm
  maps/unused/atlas_old.dmm
  maps/unused/cogmap_nornwalls.dmm
  maps/unused/destiny_xmas_2017.dmm
  maps/unused/devship.dmm
  maps/unused/donut2.dmm
  maps/unused/donut2_new_walls.dmm
  maps/unused/hainemap.dmm
  maps/unused/horizon_2019.dmm
  maps/unused/mushroom_new_walls.dmm
  maps/unused/oshan_xmas_2018.dmm
  maps/unused/syndicate_station_WIP.dmm
  maps/warwip/atlas_horizon_xmas_2019.dmm
  maps/warwip/gehenna_colony.dmm
  maps/warwip/z3_gehenna.dmm
  maps/wrestlemap.dmm
  maps/z2.dmm
Labels: size/XL
