Repository coolstation/coolstation, pull requests merged in 2024-01, with the labels that each got.

#227 Fix phonebook not opening
  code/obj/machinery/phone.dm
Labels: size/M

#228 monkeysprites for botanist apron and waistcoat vest
  icons/mob/monkey_clothes.dmi
Labels: size/XS

#229 Fix plane runtime on game close
  _std/plane.dm
  code/mob.dm
Labels: size/XS

#213 turf_persistent datums
  _std/pathfinding.dm
  code/RobustLight2.dm
  code/SimpleLight.dm
  code/atom.dm
  code/datums/abilities/wizard/phaseshift.dm
  code/datums/flock/flock.dm
  code/modules/admin/diagnostics.dm
  code/modules/atmospherics/FEA_system.dm
  code/modules/atmospherics/FEA_turf_tile.dm
  code/modules/fluids/air.dm
  code/modules/materials/Mat_ProcsDefines.dm
  code/procs/helpers.dm
  code/turf/floors.dm
  code/turf/floors_airless.dm
  code/turf/turf.dm
  code/turf/turf_persistent.dm
  coolstation.dme
Labels: size/XL

#231 monkeysprites for 14 labcoats that were missing them
  icons/mob/monkey_clothes.dmi
Labels: size/XS

#232 monkeysprite for straight jacket
  icons/mob/monkey_clothes.dmi
Labels: size/XS

#233 Nod AND Nods
  code/datums/emotes/emote_parent.dm
  code/datums/emotes/emote_simple.dm
  code/modules/interface/action_associations.dm
  code/modules/interface/keybind_style.dm
Labels: size/S

#238 Change default map to chunk
  maps/config/standard.dm
Labels: size/XS

#239 Add returns to microwave attackby
  code/obj/machinery/microwave.dm
Labels: size/XS

#240 monkeysprites for 6 departmental winter coats
  icons/mob/monkey_clothes.dmi
Labels: size/XS

#241 Camera coverage optimization
  code/global.dm
  code/mob/dead/ai-camera.dm
Labels: size/M

#242 Custom pronouns
  code/datums/preferences.dm
  code/datums/pronouns.dm
  code/datums/savefile.dm
  code/mob.dm
  code/procs/mob_procs.dm
Labels: size/L

#243 Adds grubsteak and various grubfood recipes
  code/datums/cookingrecipes.dm
  code/mob/living/critter/grub.dm
  code/modules/food_and_drink/ingredients.dm
  code/modules/food_and_drink/sandwiches.dm
  code/modules/food_and_drink/snacks.dm
  icons/obj/foodNdrink/food.dmi
  icons/obj/foodNdrink/food_bread.dmi
  icons/obj/foodNdrink/food_ingredient.dmi
Labels: size/M

#245 ttv inhand sprite fix
  icons/mob/inhand/hand_general.dmi
Labels: size/XS

#246 shockurdonks
  code/modules/food_and_drink/snacks.dm
Labels: size/S

#247 Adds new hairstyle "Untidy"
  code/datums/customization_styles.dm
  icons/mob/human_hair.dmi
Labels: size/XS

#248 try and fix some switch cases
  _std/macros/procs.dm
  code/mob/living/critter/ai.dm
  code/modules/atmospherics/portable/canister.dm
  code/modules/chemistry/Reagents-PoisonEtc.dm
  code/turf/floors.dm
Labels: size/S

#249 Airlock Cycling Framework
  code/obj/machinery/door/airlock.dm
  icons/obj/doors/Door1.dmi
Labels: size/M

#250 Add twirl hotkey (ported from goonstation #9908)
  browserassets/html/admin/hotkeys.html
  code/modules/interface/action_associations.dm
  code/modules/interface/keybind_style.dm
Labels: size/XS

#252 Glass crunches underfoot more
  code/obj/item/material.dm
Labels: size/XS

#251 Semicolon for main radio (ported from goonstation #6423)
  code/mob/dead/ai-camera.dm
  code/mob/living.dm
  code/modules/interface/action_associations.dm
  code/modules/interface/keybind_style.dm
  code/procs/mobprocs/chatprocs.dm
Labels: size/S

#253 Add Pride Bedsheets to the uniform manufacturers
  code/datums/manufacturing.dm
  code/obj/machinery/manufacturer.dm
Labels: size/L

#254 Prevent Mechcomp on open access panels (ported from goonstation #5844 and #6506)
  code/datums/components/mechComp_signals.dm
Labels: size/XS

#258 I WANT THOSE PICTURES OF SPIDER MAN
  code/mob/living/critter/spider.dm
  icons/misc/critter.dmi
Labels: size/M
