Repository coolstation/coolstation, pull requests merged in 2024-10, with the labels that each got.

#281 new walls woah
  code/turf/turf_autoalign.dm
  code/turf/walls.dm
  icons/turf/walls_auto_color.dmi
  icons/turf/walls_rivet.dmi
Labels: size/M

#285 Bayou Bend Dock-N-Go (WIP)
  _std/__build.dm
  _std/mapDefines.dm
  code/map.dm
  code/obj/item/paper.dm
  maps/bayoubend.dmm
  maps/config/bayoubend.dm
  maps/config/map.dm
  maps/klushywip/bayoubend.dmm
Labels: size/XXL

#290 Bayou Bend more thiiiings
  code/area.dm
  code/global.dm
  code/map.dm
  code/obj/machinery/computer/shuttle.dm
  maps/klushywip/bayoubend.dmm
  maps/z4_blank.dmm
Labels: size/XXL

#193 Jucier Party Barge (Needs Work)
  assets/maps/prefabs/juicerpartybarge.dmm
Labels: size/M

#291 Adds PURPLE toxins-specific vendomat with larger inventory
  code/modules/vending/vending.dm
  icons/obj/machines/vending.dmi
  maps/cogmap.dmm
  maps/warwip/chunk.dmm
  maps/warwip/z3_gehenna.dmm
Labels: size/L

#292 Fix atmos analyzer inhand disappearing when upgraded
  code/obj/item/device/scanners.dm
Labels: size/XS
