Repository coolstation/coolstation, pull requests merged in 2024-12, with the labels that each got.

#310 bandaid for artifact restock
  code/modules/economy/shippingmarket.dm
Labels: size/XS

#313 Make head injuries cause brain damage
  code/mob/melee_attack_procs.dm
  code/obj/item.dm
Labels: size/XS

#311 Bayou shipyard
  assets/maps/random_ships/30x25/hull1.dmm
  assets/maps/random_ships/30x25/hull2.dmm
  assets/maps/random_ships/30x25/hull3.dmm
  assets/maps/random_ships/3x3/cargo1.dmm
  assets/maps/random_ships/3x3/cargo2.dmm
  assets/maps/random_ships/3x3/clownroom.dmm
  assets/maps/random_ships/3x3/explosive1.dmm
  assets/maps/random_ships/3x3/explosive2.dmm
  assets/maps/random_ships/5x3/cargo1.dmm
  assets/maps/random_ships/5x3/livingQuarters.dmm
  code/area.dm
  code/modules/worldgen/random_rooms.dm
  code/modules/worldgen/random_ships.dm
  code/obj/machinery/computer/shuttle.dm
  code/procs/gamehelpers.dm
  coolstation.dme
  icons/map-editing/random-rooms/30x25.dmi
  maps/klushywip/bayoubend.dmm
  maps/z2.dmm
  maps/z4_blank.dmm
  strings/changelog.txt
Labels: size/XXL

#315 Bayou bend additions, fixes, and ship prefabs
  assets/maps/random_ships/30x25/hull1.dmm
  assets/maps/random_ships/3x3/barthole_10.dmm
  assets/maps/random_ships/3x3/orehold.dmm
  assets/maps/random_ships/3x3/shipdistillery.dmm
  assets/maps/random_ships/5x3/cargo2.dmm
  assets/maps/random_ships/5x3/cryogenics.dmm
  assets/maps/random_ships/5x3/serverroom.dmm
  maps/klushywip/bayoubend.dmm
  strings/changelog.txt
Labels: size/XL

#316 RED ALERT!!!! I FUCKED UP THE BAYOU
  assets/maps/random_ships/3x3/barthole_10.dmm
  maps/klushywip/bayoubend.dmm
Labels: size/M
