Repository coolstation/coolstation, pull requests merged in 2025-04, with the labels that each got.

#554 Phones and posters again (unused robot icons as well)
  icons/obj/bots/tallbots.dmi
  maps/warwip/the_crag.dmm
Labels: size/L

#559 fueltank resprite :)
  code/modules/chemistry/tools/dispensers.dm
  icons/obj/objects.dmi
Labels: size/M

#555 Adds milk to the allergy trait allergen list
  code/datums/traits.dm
Labels: size/XS

#560 fix colored clown masks turn into normal clown mask
  code/obj/item/clothing/masks.dm
Labels: size/S

#561 Further UI Fixes, including character previews and DPI scaling.
  _std/defines/component_defines.dm
  browserassets/js/chui/chui.js
  browserassets/js/clothingbooth.js
  browserassets/js/go.js
  browserassets/js/jquery.js
  browserassets/js/zoldorf.js
  browserassets/tgui/tgui-panel.bundle.js
  browserassets/tgui/tgui.bundle.js
  code/datums/character_preview.dm
  code/datums/hud.dm
  code/datums/preferences.dm
  code/modules/sound/djpanel.dm
  code/modules/tgui/tgui.dm
  code/modules/tgui/tgui_window.dm
  code/modules/vending/clothingbooth.dm
  tgui/packages/tgui/backend.ts
  tgui/packages/tgui/drag.js
Labels: size/L

#562 Fixes up the custom job maker
  code/datums/controllers/job_controls.dm
Labels: size/M

#563 Fugu shenanigans
  code/modules/fishing/fish.dm
Labels: size/XS

#564 Revert "fix vr nullspace"
  code/mob/living/carbon/human/virtual.dm
Labels: size/XS

#567 WYSIWYG by TDHooligan!
  code/WorkInProgress/ItemSpecials.dm
  code/global.dm
  code/mob/input.dm
  code/modules/admin/admin.dm
  code/procs/gamehelpers.dm
Labels: size/M

#566 MULEbots pathfind between navbeacons and PDAs via pings.
  _std/pathfinding.dm
  code/modules/robotics/bot/bot_parent.dm
  code/modules/robotics/bot/mulebot.dm
  code/obj/decal.dm
  code/obj/item/device/pda2/bot_control.dm
  code/obj/item/device/pda2/cartridges.dm
  code/obj/machinery/door/door_parent.dm
  code/obj/machinery/navbeacon.dm
  code/turf/turf.dm
  code/z_adventurezones/luna.dm
  maps/cogmap.dmm
  maps/destiny.dmm
  maps/donut2.dmm
  maps/donut3.dmm
  maps/donut3_xmas.dmm
  maps/kondaru.dmm
  maps/ozymandias.dmm
  maps/pamgoc.dmm
  maps/setpieces/AIBM_hospital.dmm
  maps/setpieces/AIBM_lunar.dmm
  maps/setpieces/AIBM_spacejunk.dmm
  maps/setpieces/dadzone.dmm
  maps/warwip/z3_gehenna.dmm
  maps/z2.dmm
  maps/z3.dmm
Labels: size/XXL

#569 The war on drugs begins...
  code/modules/atmospherics/machinery/unary/cryo_cell.dm
  code/modules/chemistry/Chemistry-Reagents.dm
  code/modules/chemistry/Reagents-Drugs.dm
  code/modules/chemistry/Reagents-Medical.dm
  code/modules/chemistry/Reagents-PoisonEtc.dm
  code/obj/item/device/pda2/scanners.dm
  code/obj/item/device/scanners.dm
  code/procs/scanprocs.dm
Labels: size/M

#570 CHUI Refresh
  browserassets/css/chui/themes/default/default.css
  maps/wackwip/Tumbleweed.dmm
Labels: size/XXL

#565 adds recoil
  code/client.dm
  code/modules/gunse/modular_guns.dm
  code/modules/recoil/recoil_controller.dm
  code/obj/item/gun/gun_parent.dm
  code/procs/helpers.dm
  coolstation.dme
  interface/skin.dmf
Labels: size/L

#571 Json saves
  browserassets/tgui/tgui.bundle.js
  code/datums/preferences.dm
  code/datums/savefile.dm
  code/procs/helpers.dm
  tgui/packages/tgui/interfaces/CharacterPreferences/CharacterTab.tsx
Labels: size/L

#572 SPEND MONEY AT THE CREDIT STORE???
  code/WorkInProgress/zamujasa.dm
  code/datums/components/storage_viscontents.dm
  code/datums/components/transform_on_pickup.dm
  code/obj/storage/crates.dm
  code/obj/storage/gang_crate.dm
  code/obj/storage/large_storage_parent.dm
  code/obj/storage/vis_storage_controller.dm
  coolstation.dme
  icons/obj/items/storage.dmi
  icons/obj/large_storage.dmi
Labels: size/XXL

#576 Gun sprites into the gunse refactor branch
  code/WorkInProgress/zamujasa.dm
  code/modules/gunse/_modular_guns.dm
  code/modules/gunse/gunse_it.dm
  code/modules/gunse/gunse_nt.dm
  code/modules/gunse/modular_gun_parts.dm
  code/modules/vending/vending.dm
  icons/obj/items/modular_guns/barrels.dmi
  icons/obj/items/modular_guns/grips.dmi
  icons/obj/items/modular_guns/receivers.dmi
  icons/obj/items/modular_guns/stocks.dmi
Labels: size/L

#574 Port interesting melee weapons and special attacks by Hooligan and Mora
  _std/__std.dme
  _std/compare.dm
  _std/defines/atom.dm
  _std/defines/component_defines.dm
  _std/defines/item.dm
  _std/macros/items.dm
  browserassets/images/tooltips/heavyswing.png
  browserassets/images/tooltips/jab.png
  code/WorkInProgress/mantaObjects.dm
  code/WorkInProgress/zamujasa.dm
  code/datums/components/bloodflick.dm
  code/datums/emotes/emote_complex.dm
  code/datums/gamemodes/gangwar.dm
  code/datums/hud.dm
  code/datums/hud/vision_impair.dm
  code/datums/movement_modifier/movement_modifiers.dm
  code/mob.dm
  code/mob/living.dm
  code/modules/forensics/atom_forensic.dm
  code/modules/items/specials/ItemSpecials.dm
  code/modules/status_system/statusEffects.dm
  code/obj/decal/cleanable.dm
  code/obj/item.dm
  code/obj/item/basketball.dm
  code/obj/item/cigarette.dm
  code/obj/item/device/igniter.dm
  code/obj/item/kitchen.dm
  code/obj/item/misc_weapons.dm
  code/obj/item/mops_cleaners.dm
  code/obj/item/tool/tools.dm
  code/obj/item/tool/weldingtool.dm
  code/obj/machinery/door/airlock.dm
  code/turf/walls.dm
  coolstation.dme
  icons/effects/96x96.dmi
  icons/effects/effects.dmi
  icons/effects/meleeeffects.dmi
  icons/obj/decals/gang_tags.dmi
  icons/obj/decals/graffiti.dmi
  icons/obj/items/items.dmi
  icons/obj/items/weapons.dmi
  icons/ui/statussystem.dmi
  sound/effects/graffiti_hit.ogg
  sound/impact_sounds/bat_wood_crit.ogg
  sound/impact_sounds/metal_thump.ogg
  sound/items/graffitishake.ogg
  sound/items/graffitispray3.ogg
Labels: size/XXL

#575 Airlock wire groups
  code/area.dm
  code/global.dm
  code/obj/machinery/door/airlock.dm
Labels: size/M

#578 Backslung
  code/modules/gunse/_modular_guns.dm
  code/obj/item/gun/kinetic.dm
  code/obj/item/misc_weapons.dm
  icons/mob/back.dmi
Labels: size/S
