Repository coolstation/coolstation, pull requests merged in 2025-02, with the labels that each got.

#401 Fix powernet mechanic component mangling packets
  code/WorkInProgress/MechanicsNetworkCon.dm
Labels: size/XS

#391 Ports last gasps from goonstation
  code/mob/living.dm
  code/mob/living/carbon.dm
  code/mob/living/carbon/human/virtual.dm
  code/mob/living/silicon.dm
  code/procs/mobprocs/chatprocs.dm
Labels: size/M

#386 Ports counting mechcomp
  _std/math.dm
  code/WorkInProgress/MechanicMadness.dm
  code/modules/vending/vending.dm
Labels: size/L

#385 Refactor control unit execution process
  code/WorkInProgress/MechanicMC14500.dm
Labels: size/M

#384 Output GPS coords in signal list format
  code/obj/item/device/gps.dm
Labels: size/XS

#383 Support backslash escapes in mechcomp packets, unify signal splitting
  _std/__std.dme
  _std/macros/list.dm
  code/WorkInProgress/MechanicMadness.dm
Labels: size/S

#376 ports updatepaths and mapmerge2 updates up to 28.1.2025
  tools/UpdatePaths/LICENSE.MD
  tools/UpdatePaths/Update Paths.bat
  tools/UpdatePaths/__main__.py
  tools/UpdatePaths/readme.md
  tools/mapmerge2/Run Before Committing.bat
  tools/mapmerge2/convert.py
  tools/mapmerge2/dmm.py
  tools/mapmerge2/fixup.py
  tools/mapmerge2/merge_driver.py
Labels: size/XL

#403 adds logistics radio to captain, HoP and radio show host
  code/obj/item/device/radios/headsets.dm
Labels: size/XS

#409 Adds lastgasp() to various slips
  code/WorkInProgress/bowling.dm
  code/datums/controllers/process/forcedMovement.dm
  code/mob/living/carbon.dm
  code/modules/fluids/fluid_core.dm
  code/obj/decal.dm
  code/obj/decal/cleanable.dm
  code/obj/item/clown_items.dm
  code/obj/item/device/pda2/pda2.dm
  code/procs/mob_procs.dm
Labels: size/S

#358 you may no longer roll in the grave while unconscious or dead
  code/mob/input.dm
  code/modules/interface/mob_input.dm
Labels: size/XS

#411 Fix DWAINE scripts eventually breaking the whole mainframe
  code/modules/networks/computer3/mainframe2/shell.dm
Labels: size/XS

#375 area turf lists
  code/area.dm
  code/procs/gamehelpers.dm
  code/world.dm
  code/z_dmm_suite/reader.dm
Labels: size/M

#414 Color radio inputs based on chosen channel; support last gasps on radio hotkeys
  _std/defines/radio.dm
  code/mob/dead/ai-camera.dm
  code/mob/living.dm
  code/modules/interface/action_associations.dm
  code/modules/interface/skin_input_box.dm
  code/procs/mobprocs/chatprocs.dm
  code/world.dm
  interface/skin.dmf
Labels: size/L

#415 Respawn As Job admin verb
  code/modules/admin/admin_verbs.dm
  strings/admin_changelog.txt
Labels: size/S

#417 Respawn as Job respawns you in place
  code/mob/new_player.dm
  code/modules/admin/admin_verbs.dm
Labels: size/S

#419 Another collection of input skin changes
  code/mob/living.dm
  code/modules/interface/action_associations.dm
  code/modules/interface/skin_input_box.dm
  code/procs/mobprocs/chatprocs.dm
  interface/skin.dmf
Labels: size/M

#418 Nurses spawn with random scrubs and a medical headset
  code/datums/jobs.dm
Labels: size/XS

#422 fixes some missed sprites (.dmi edit only)
  icons/turf/floors.dmi
Labels: size/XS

#420 AI eyebot can use secure radio!
  code/mob/living.dm
Labels: size/XS

#421 Require harm intent to adjust shape of table with screwdriver
  code/obj/table.dm
Labels: size/XS

#425 The Sittening
  code/obj/furniture/chair.dm
  code/obj/furniture/couch.dm
  code/obj/item/furniture_parts/seat_parts.dm
  code/obj/stool.dm
  icons/obj/furniture/bench_navy.dmi
  icons/obj/furniture/bench_orange.dmi
  icons/obj/furniture/bench_purple.dmi
  icons/obj/furniture/chairs.dmi
Labels: size/M

#427 Basic slidekicks and epic slidekicks
  _std/macros/mob_properties.dm
  code/WorkInProgress/ObjectProperties.dm
  code/datums/movement_modifier/movement_modifiers.dm
  code/mob/living.dm
  code/mob/living/carbon/human.dm
  code/mob/living/life/stuns_lying.dm
  code/modules/status_system/statusEffects.dm
  code/obj/item/clothing/shoes.dm
Labels: size/L

#428 lizard alt gas mask alt sprite
  icons/mob/lizard_clothes.dmi
Labels: size/XS

#429 Fixes being able to slidekick when you shouldn't
  code/mob/living/carbon/human.dm
Labels: size/L

#426 Adds pufferfish and fugu to the game
  code/datums/commodity.dm
  code/datums/jobs.dm
  code/datums/supply_packs.dm
  code/datums/traits.dm
  code/modules/chemistry/Reagents-PoisonEtc.dm
  code/modules/economy/trader.dm
  code/modules/fishing/fish.dm
  code/modules/food_and_drink/ingredients.dm
  icons/obj/foodNdrink/food_fish.dmi
  icons/obj/foodNdrink/food_ingredient.dmi
Labels: size/L

#430 Adds maintenance arrears program to cyborg and AI pdas
  code/obj/item/device/pda2/cartridges.dm
Labels: size/XS

#433 Replaces the dark mode theme with a very cool theme
  browserassets/css/browserOutput.css
  browserassets/js/browserOutput.js
  code/client.dm
  interface/skin.dmf
Labels: size/M

#434 Adds fabbable chemical cannisters
  code/datums/manufacturing.dm
  code/modules/chemistry/tools/fuel_tanks.dm
  code/obj.dm
  code/obj/machinery/manufacturer.dm
  code/obj/storage/large_storage_parent.dm
  icons/mob/inhand/hand_general.dmi
  icons/obj/objects.dmi
Labels: size/M

#435 Add a cool theme switcher and a charcoal theme
  browserassets/css/browserOutput.css
  browserassets/js/browserOutput.js
  code/client.dm
  interface/skin.dmf
Labels: size/M

#437 Nerfs Hemotoxin and makes bleeding more noticeable before being very dangerous
  code/mob/living/life/blood.dm
  code/modules/chemistry/Reagents-PoisonEtc.dm
Labels: size/S

#436 [ opens last messaged radio channel
  code/client.dm
  code/modules/interface/keybind_style.dm
  code/obj/item/device/radio.dm
  code/procs/jobprocs.dm
  code/procs/mobprocs/chatprocs.dm
  interface/skin.dmf
Labels: size/M

#439 Fix rebinding skinned inputs
  code/modules/interface/action_associations.dm
  code/modules/interface/keymap.dm
Labels: size/S

#440 Whisper and general and last radio are rebindable
  code/modules/interface/action_associations.dm
  code/modules/interface/keybind_style.dm
Labels: size/XS

#441 Double semilcolons talks on general channel
  code/procs/helpers.dm
Labels: size/XS

#444 ooc and looc inputs are skinned; custom colors for admins and mentors
  code/modules/admin/admin_verbs.dm
  code/modules/interface/action_associations.dm
  code/modules/interface/skin_input_box.dm
  interface/skin.dmf
Labels: size/M

#445 Fix furnace crate typo
  code/datums/supply_packs.dm
  code/modules/power/TEG.dm
Labels: size/XS

#404 the slippery and slidey water slide
  code/modules/chemistry/tools/fuel_tanks.dm
  code/obj/machinery/waterslide.dm
  coolstation.dme
  icons/obj/stationobjs.dmi
Labels: size/L

#448 add hiding items under floortiles
  _std/defines/component_defines.dm
  code/obj/item/mousetrap.dm
  code/turf/floors.dm
  code/turf/turf_persistent.dm
Labels: size/M

#452 Tactical Turtleneck and Turdsuit Icon Fix
  icons/mob/jumpsuits/worn_js_misc.dmi
Labels: size/XS

#451 Restyle the window decorations on chui windows
  browserassets/css/chui/themes/default/default.css
Labels: size/M

#449 tweak job panel for new chui theme
  code/datums/preferences.dm
Labels: size/XS

#450 Style player options and view variables
  code/datums/datumvars.dm
  code/modules/admin/player_panel.dm
Labels: size/XS

#453 fix the default.css css file
  browserassets/css/chui/themes/default/default.css
Labels: size/XS

#454 Removes a racist disease.
  code/datums/gamemodes/monkey.dm
  code/modules/chemistry/Reagents-Diseases.dm
  code/modules/medical/diseases/jungle_fever.dm
  code/modules/networks/computer3/med_rec.dm
  coolstation.dme
Labels: size/L

#470 2 map flags related to scarcity
  code/modules/power/apc.dm
  code/modules/power/cell.dm
  code/modules/power/furnace.dm
  code/obj/machinery/glass_recycler.dm
  code/obj/machinery/manufacturer.dm
  code/world.dm
Labels: size/L

#456 Fix latejoin chui theme and chuify it
  code/datums/jobs.dm
  code/mob/new_player.dm
Labels: size/M

#457 The nefarious hot roller
  code/modules/materials/Mat_RawMaterials.dm
  code/obj/machinery/metal_rolling.dm
  coolstation.dme
  icons/obj/stationobjs.dmi
  sound/machines/hot_loop_process_1.ogg
  sound/machines/hot_roller_loop.ogg
  sound/machines/hot_roller_loop_temp.ogg
Labels: size/L

#463 Compost some corpses today!
  code/modules/chemistry/tools/dispensers.dm
Labels: size/M

#461 Fake attacker touchups and enhancements
  code/WorkInProgress/AnimationLibrary.dm
  code/datums/components/hallucinations.dm
  code/mob/living.dm
  code/modules/chemistry/Reagents-Drugs.dm
Labels: size/L

#469 THE PLANTENING
  code/WorkInProgress/AnimationLibrary.dm
  code/obj/decorations.dm
  code/turf/floors.dm
  icons/obj/large/64x64.dmi
  icons/turf/floors.dmi
Labels: size/M

#465 Adds Vertigo compound, a drug that messes with muscle coordination
  code/modules/chemistry/Chemistry-Recipes.dm
  code/modules/chemistry/Reagents-PoisonEtc.dm
Labels: size/M

#460 Resprites the circular saws, and adds a nasty variant
  code/datums/disease.dm
  code/modules/chemistry/Reagents-Diseases.dm
  code/modules/medical/diseases/infection.dm
  code/modules/medical/surgery_tools.dm
  icons/obj/surgery.dmi
Labels: size/M

#473 Further refine latejoin screen
  code/datums/jobs.dm
  code/mob/new_player.dm
Labels: size/M

#467 Jab people with syringes
  code/modules/chemistry/tools/syringes.dm
Labels: size/M

#477 Smart scroll bar margins for chui
  browserassets/css/chui/themes/default/default.css
  browserassets/js/jquery.nanoscroller.min.js
  code/mob/new_player.dm
Labels: size/XXL

#478 Disable chui for QM computer
  code/chui/window.dm
  code/obj/machinery/computer/QM_supply.dm
Labels: size/S

#479 Ports action bars to syringes.
  code/datums/controllers/action_controls.dm
  code/modules/chemistry/tools/syringes.dm
Labels: size/L

#468 Changes the behavior of cloth rag chokes
  code/obj/item/grab.dm
Labels: size/XS

#482 Chucking appliances
  _std/macros/mob_properties.dm
  code/datums/manufacturing.dm
  code/mob/living/carbon/human.dm
  code/mob/living/carbon/human/machoman.dm
  code/modules/chemistry/tools/food_and_drink.dm
  code/modules/chemistry/tools/fuel_tanks.dm
  code/obj.dm
  code/obj/item/clothing/gloves.dm
  code/obj/item/clothing/shoes.dm
  code/obj/item/lifting_wrapper.dm
  code/obj/machinery/espresso.dm
  code/obj/machinery/glass_recycler.dm
  code/obj/machinery/microwave.dm
  code/obj/submachine/cooking.dm
Labels: size/L

#459 Differentiates functioning of Ether and Morphine
  code/modules/chemistry/Reagents-Medical.dm
  code/modules/medical/diseases/malady.dm
Labels: size/M

#485 Turbopunk distribution
  code/datums/syndicate_buylist.dm
  code/obj/random_spawners.dm
Labels: size/XS

#484 Fix hallucinations nulling vars on dupe
  code/datums/components/hallucinations.dm
Labels: size/S

#483 Big overhaul to burning chemicals
  _std/defines/layer.dm
  code/WorkInProgress/Particles.dm
  code/datums/controllers/process/chemistry.dm
  code/datums/controllers/process/fireflash.dm
  code/datums/emotes/emote_huge.dm
  code/mob/living/carbon.dm
  code/mob/living/critter/small_animal.dm
  code/modules/atmospherics/FEA_fire.dm
  code/modules/chemistry/Chemistry-Holder.dm
  code/modules/chemistry/Chemistry-Reactions.dm
  code/modules/chemistry/Chemistry-Reagents.dm
  code/modules/chemistry/Reagents-Base.dm
  code/modules/chemistry/Reagents-ExplosiveFire.dm
  code/modules/chemistry/Reagents-FoodDrink.dm
  code/modules/chemistry/Reagents-Medical.dm
  code/modules/chemistry/Reagents-Misc.dm
  code/modules/chemistry/tools/dispensers.dm
  code/modules/chemistry/tools/extinguisher.dm
  code/modules/chemistry/tools/fuel_tanks.dm
  code/modules/chemistry/tools/grenades.dm
  code/modules/medical/surgery_procs.dm
  code/modules/projectiles/special.dm
  code/obj.dm
  code/obj/effects/bad_smoke.dm
  code/obj/effects/water.dm
  code/obj/item.dm
  code/obj/item/cigarette.dm
  code/procs/fireflash.dm
  coolstation.dme
  icons/effects/particles.dmi
Labels: merge conflict, size/XXL

#481 Fix a runtime I introduced with interact_particle on walls
  code/WorkInProgress/AnimationLibrary.dm
  code/turf/walls.dm
Labels: size/XS

#486 Crag moment
  _std/__build.dm
Labels: size/XS

#488 Drowsiness doesn't KO you for 10 whole seconds
  code/mob/living/life/disability.dm
  code/modules/chemistry/Reagents-Medical.dm
Labels: size/XS

#490 fixes minor bug in shitty_grill
  code/obj/machinery/shitty_grill.dm
Labels: size/XS

#489 Pitfall port
  _std/defines/atom.dm
  _std/defines/component_defines.dm
  code/WorkInProgress/AnimationLibrary.dm
  code/WorkInProgress/Azungarstuff.dm
  code/WorkInProgress/ZeWakasStuff.dm
  code/WorkInProgress/mantaObjects.dm
  code/area.dm
  code/atom.dm
  code/datums/components/_component.dm
  code/datums/components/pitfall.dm
  code/datums/controllers/throwing_controls.dm
  code/modules/fluids/fluid_objects.dm
  code/modules/fluids/fluid_turf.dm
  code/modules/shuttles/transit_vehicle.dm
  code/modules/sound/soundCache.dm
  code/turf/floors.dm
  code/turf/turf.dm
  code/z_adventurezones/icemoon.dm
  code/z_adventurezones/luna.dm
  coolstation.dme
  sound/effects/slidewhistlefall.ogg
Labels: size/XL
