Repository coolstation/coolstation, pull requests merged in 2025-01, with the labels that each got.

#314 Getting hit in the leg now matters
  code/obj/item.dm
Labels: size/XS

#317 Revamped Bayou cargo and scrapper role
  _std/defines/access.dm
  assets/maps/random_ships/30x25/scrap1.dmm
  code/datums/jobs.dm
  code/lists/jobs.dm
  code/map.dm
  code/obj/access_spawn.dm
  code/obj/item/clothing/uniforms.dm
  code/obj/item/device/pda2/pda2.dm
  code/obj/item/device/radios/headsets.dm
  code/obj/machinery/computer/card.dm
  code/procs/access.dm
  maps/klushywip/bayoubend.dmm
  strings/changelog.txt
Labels: merge conflict, size/XL

#320 Move the QMs office to cargo on chunk
  maps/warwip/chunk.dmm
Labels: size/XXL

#322 corrects discord invite in vpn kick message
  code/client.dm
Labels: size/XS

#321 90fps option
  _std/defines/lag.dm
  code/client.dm
  interface/skin.dmf
Labels: size/S

#329 kick security in face 9 times
  code/WorkInProgress/Azungarstuff.dm
  code/datums/jobs.dm
  code/obj/item/storage/ammo_pouches.dm
  code/obj/item/storage/backpack_belt_etc.dm
Labels: size/M

#324 Save more settings to the dang cloud thanks
  code/client.dm
  code/datums/gameticker.dm
Labels: size/L

#323 doors autoclose properly
  code/obj/machinery/door/airlock.dm
  code/obj/machinery/door/door_parent.dm
Labels: size/M

#333 Carpet
  code/turf/floors.dm
  icons/turf/floors.dmi
Labels: size/S

#334 Fix mail chute UI crashing on weird modes
  code/WorkInProgress/recycling/disposal_chute.dm
  code/WorkInProgress/recycling/mail_chute.dm
  tgui/packages/tgui/interfaces/DisposalChute/index.tsx
  tgui/packages/tgui/interfaces/DisposalChute/type.ts
Labels: size/M

#338 Payoutforscrap
  _std/__build.dm
  assets/maps/random_ships/room/3x3/clownroom.dmm
  assets/maps/random_ships/room/3x3/explosive1.dmm
  assets/maps/random_ships/scrap1.dmm
  code/area.dm
  code/modules/worldgen/random_ships.dm
  code/obj/machinery/computer/shuttle.dm
  code/procs/gamehelpers.dm
  maps/klushywip/bayoubend.dmm
  strings/changelog.txt
Labels: size/XL

#343 Adds scrap walls for fast-pace salvaging
  assets/maps/random_ships/scrap1.dmm
  code/turf/walls.dm
  icons/turf/walls.dmi
  maps/z3.dmm
Labels: size/XL

#347 old revolvar
  icons/obj/items/gun.dmi
Labels: size/XS

#352 gas mixer ui updates when you click the buttons
  code/modules/atmospherics/machinery/mixer.dm
  code/obj/machinery/computer/general_air_control.dm
Labels: size/XS

#354 Scrapping ships
  assets/maps/random_ships/30x25/hull_escape_crash.dmm
  assets/maps/random_ships/30x25/hull_tow_truck.dmm
Labels: size/XXL

#353 updates bootstrap from goonstation
  buildByond.conf
  tools/bootstrap/python
  tools/bootstrap/python.bat
  tools/bootstrap/python36._pth
  tools/bootstrap/python_.ps1
Labels: size/M

#350 prevent the pregame timer from ticking down if there are no clients
  code/datums/gameticker.dm
Labels: size/XS

#355 changes windows id of many computers
  code/WorkInProgress/simroom.dm
  code/datums/embedded_controller.dm
  code/modules/economy/stocks/stock_machine.dm
  code/modules/power/TEG.dm
  code/modules/power/turbine.dm
  code/obj/machinery/computer/QM_order.dm
  code/obj/machinery/computer/door_control.dm
  code/obj/machinery/computer/general_air_control.dm
  code/obj/machinery/computer/pod.dm
  code/obj/machinery/computer/robotics.dm
  code/obj/mining.dm
Labels: size/M

#348 radio sprites
  icons/obj/items/device.dmi
Labels: size/XS

#356 adds loafer to bayou bend
  maps/klushywip/bayoubend.dmm
Labels: size/L

#359 (probably) fixes stuck typing indicator
  code/mob.dm
  code/mob/living.dm
  code/procs/mobprocs/chatprocs.dm
Labels: size/M

#365 connects all printers to network on bayou bend and makes wall phones and air alarms only accessible from inside the room
  maps/klushywip/bayoubend.dmm
Labels: size/L

#370 adds a mobile disposals pipe layer to bayou bend
  maps/klushywip/bayoubend.dmm
Labels: size/L

#372 adds the pda cartridge vendor and mainframe radio to bayou bend
  maps/klushywip/bayoubend.dmm
Labels: size/M

#374 Port buffering mechcomp from goon
  code/WorkInProgress/MechanicMadness.dm
  code/WorkInProgress/MechanicProcess.dm
  code/atom.dm
  code/global.dm
  code/modules/vending/vending.dm
  coolstation.dme
  icons/misc/mechanicsExpansion.dmi
Labels: size/L

#367 makes dirt layer under pipes (and other atmos stuff)
  _std/defines/layer.dm
  code/obj/decal/cleanable.dm
Labels: size/XS

#380 Logistics lockers
  code/obj/storage/secure_closets.dm
  maps/bobwip/bobmap.dmm
  maps/cogmap.dmm
  maps/klushywip/bayoubend.dmm
  maps/unused/donut2.dmm
  maps/warwip/chunk.dmm
  maps/warwip/gehenna_colony.dmm
  maps/z2.dmm
  maps/z5.dmm
Labels: size/L

#389 degenders hair + some new styles
  code/datums/customization_styles.dm
  code/datums/preferences.dm
  icons/mob/human_hair.dmi
Labels: size/L

#393 Gives QM a separate PDA to Cargo Techs
  code/datums/jobs.dm
  code/obj/item/device/pda2/cartridges.dm
  code/obj/item/device/pda2/pda2.dm
  code/obj/item/storage/clothing.dm
  icons/obj/items/pda.dmi
Labels: size/M

#392 security neutralized
  coolstation.dme
  icons/mob/head.dmi
  icons/mob/overcoats/worn_suit_armor.dmi
  icons/obj/clothing/item_hats.dmi
  icons/obj/clothing/overcoats/item_suit_armor.dmi
Labels: size/XS
