Repository coolstation/coolstation, pull requests merged in 2025-07, with the labels that each got.

#580 Adds a new 'No Evil' admin verb
  code/modules/admin/admin_verbs.dm
  code/modules/admin/randomverbs.dm
  strings/admin_changelog.txt
Labels: size/M

#589 Resprite of coffee related items and objects
  code/modules/chemistry/tools/food_and_drink.dm
  code/obj/machinery/espresso.dm
  icons/obj/foodNdrink/drinks.dmi
  icons/obj/foodNdrink/espresso.dmi
Labels: size/XS

#585 Crag changes
  code/WorkInProgress/gehenna.dm
  code/datums/jobs.dm
  code/modules/sound/sound.dm
  code/obj/debug_tools.dm
  code/obj/decal.dm
  code/obj/decorations.dm
  code/obj/railway.dm
  icons/obj/large/32x64.dmi
  icons/obj/machines/computer.dmi
  icons/obj/machines/computer_screens.dmi
  icons/obj/railway.dmi
  maps/tool_maps/atmos_palette.dmm
  maps/warwip/the_crag.dmm
  maps/warwip/z3_the_crag.dmm
Labels: size/XXL

#586 Lamp
  icons/obj/lighting.dmi
Labels: size/XS

#592 Silly book
  code/obj/item/book.dm
  icons/obj/items/writing.dmi
  interface/skin.dmf
  maps/cogmap.dmm
  maps/klushywip/bayoubend.dmm
Labels: size/M

#593 wherps
  code/modules/gunse/modular_gun_parts.dm
Labels: size/XS

#596 make the fire alarm emissive overlays work on the crag branch and not show both overlays at once and move overlay handling to update_icon which is a new proc i made so you dont have to call updateoverlays in place
  code/obj/machinery/firealarm.dm
Labels: size/M

#597 crag fixes again lol
  maps/warwip/the_crag.dmm
Labels: size/L

#598 forgor window
  maps/warwip/the_crag.dmm
Labels: size/S

#599 awa
  code/WorkInProgress/recycling/disposal_chute.dm
  code/modules/holiday/spacemas.dm
  code/modules/items/gimmick/figurine.dm
  code/modules/medical/pathology/pathogen_machines.dm
  code/modules/power/apc.dm
  code/modules/power/lighting.dm
  code/modules/power/smes.dm
  code/modules/vending/vending.dm
  code/obj/decorations.dm
  code/obj/item/device/radios/intercoms.dm
  code/obj/item/instruments.dm
  code/obj/item/paint.dm
  code/obj/machinery/door/poddoor.dm
  code/obj/machinery/firealarm.dm
  code/obj/machinery/navbeacon.dm
  code/obj/machinery/porters.dm
  code/obj/storage/large_storage_parent.dm
  icons/misc/xmas.dmi
  icons/obj/decoration.dmi
  icons/obj/doors/Door1.dmi
  icons/obj/doors/rapid_pdoor.dmi
  icons/obj/lighting.dmi
  icons/obj/machines/disposal.dmi
  icons/obj/machines/monitors.dmi
  icons/obj/machines/vending.dmi
  icons/obj/neonsigns.dmi
  icons/obj/objects.dmi
  icons/obj/radiostation.dmi
  icons/obj/stationobjs.dmi
Labels: size/L

#600 make it dim and cool as fuck in da chunk
  maps/warwip/chunk.dmm
Labels: size/L

#604 awawawa
  _std/__build.dm
  maps/warwip/the_crag.dmm
Labels: size/L

#606 crag baybeee
  _std/__build.dm
Labels: size/XS
