Repository coolstation/coolstation, pull requests merged in 2025-08, with the labels that each got.

#609 Perduta 60% WIP
  _std/__build.dm
  _std/defines/worldgen.dm
  _std/mapDefines.dm
  code/WorkInProgress/AnimationLibrary.dm
  code/WorkInProgress/magindara.dm
  code/WorkInProgress/recycling/disposal.dm
  code/area.dm
  code/datums/components/pitfall.dm
  code/datums/controllers/explosion_controls.dm
  code/datums/controllers/process/sea_hotspots.dm
  code/datums/controllers/sea_hotspot_controls.dm
  code/datums/controllers/storm_controls.dm
  code/global.dm
  code/map.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/diagnostics.dm
  code/modules/atmospherics/atmos_crafting.dm
  code/modules/chemistry/Chemistry-Dispenser.dm
  code/modules/chemistry/tools/extinguisher.dm
  code/modules/chemistry/tubes/tube.dm
  code/modules/power/cable.dm
  code/modules/shuttles/elevators.dm
  code/modules/shuttles/transit_vehicle.dm
  code/modules/worldgen/GenerateMining.dm
  code/obj.dm
  code/obj/decal.dm
  code/obj/decorations.dm
  code/obj/item.dm
  code/obj/item/building_materials.dm
  code/obj/item/clown_items.dm
  code/obj/railing.dm
  code/procs/explosion_new.dm
  code/turf/floors.dm
  code/turf/turf.dm
  code/world.dm
  coolstation.dme
  icons/effects/effects.dmi
  icons/effects/tile_effects.dmi
  icons/obj/decals/hazard_stripes.dmi
  icons/obj/large/32x48.dmi
  icons/turf/floors.dmi
  icons/turf/water.dmi
  maps/config/map.dm
  maps/config/perduta.dm
  maps/myliewip/perduta.dmm
  maps/myliewip/z5_perduta.dmm
  maps/warwip/z3_gehenna.dmm
Labels: size/XXL

#613 Beaker dyes simple
  code/modules/chemistry/Chemistry-Holder.dm
  code/modules/chemistry/Chemistry-Reagents.dm
  code/modules/chemistry/Reagents-Misc.dm
  code/procs/gamehelpers.dm
Labels: size/S

#615 Trains iteration 2
  code/WorkInProgress/trains.dm
  code/datums/preferences.dm
  code/modules/admin/admin.dm
  code/obj/decal.dm
  code/obj/mining.dm
  code/world.dm
  icons/obj/large/trains_128x96.dmi
  icons/obj/large/trains_256x128.dmi
Labels: size/XL

#282 (not WIP) Powernet data structure rework
  _std/__std.dme
  _std/macros/power.dm
  code/datums/controllers/explosion_controls.dm
  code/datums/controllers/process/machines.dm
  code/datums/gameticker.dm
  code/datums/powernet_data.dm
  code/modules/admin/diagnostics.dm
  code/modules/power/cable.dm
  code/modules/power/cable_switch.dm
  code/modules/power/conduit.dm
  code/modules/power/power_parent.dm
  code/obj/furniture/electric_chair.dm
  code/obj/grille.dm
  code/obj/item/cable_coil.dm
  code/obj/item/clothing/gloves.dm
  code/obj/machinery/manufacturer.dm
  code/world.dm
  code/z_adventurezones/sequestered_cloner.dm
Labels: size/XL
