Repository coolstation/coolstation, pull requests merged in 2025-03, with the labels that each got.

#492 New corpse mob type and morgues/bodybags that spawn them
  code/mob/living/carbon/human.dm
  code/mob/living/carbon/human/normal.dm
  code/modules/materials/Mat_RawMaterials.dm
  code/modules/medical/surgery_tools.dm
  code/obj/item/clothing/uniforms.dm
  code/obj/item/organs/skull.dm
  code/obj/morgue.dm
  icons/obj/surgery.dmi
Labels: size/L

#471 Arachnophobia accessibility trait (Round 1)
  _std/types.dm
  code/client.dm
  code/datums/components/hallucinations.dm
  code/datums/components/spider_filter.dm
  code/obj/critter/spider.dm
  coolstation.dme
  icons/effects/spider_filter.dmi
Labels: size/M

#493 The Templates And Styles Update Preview - 1.21.70.25
  _std/__std.dme
  _std/defines/pcui.dm
  browserassets/css/chui/manufacturer/manufacturer-html.css
  browserassets/css/chui/manufacturer/manufacturer-pcui.css
  code/chui/template-datum.dm
  code/chui/theme.dm
  code/chui/window.dm
  code/obj/machinery/manufacturer-template.dm
  code/obj/machinery/manufacturer.dm
  coolstation.dme
Labels: size/XL

#491 Throwing things into pitfalls is cooler
  _std/defines/atom.dm
  code/WorkInProgress/AnimationLibrary.dm
  code/atom.dm
  code/datums/components/pitfall.dm
  code/datums/controllers/throwing_controls.dm
  code/modules/status_system/statusEffects.dm
  code/obj/item/grab.dm
  code/obj/item/tank.dm
Labels: size/L

#494 Adds new directions and logic for elevators
  code/modules/fluids/fluid_turf.dm
  code/modules/shuttles/transit_vehicle.dm
  icons/turf/floors.dmi
Labels: size/L

#495 Ports a lot of upstream deployable turret changes, then adds the Juicer and Warware turrets
  code/modules/projectiles/bullet.dm
  code/modules/projectiles/projectile_parent.dm
  code/modules/projectiles/special.dm
  code/obj.dm
  code/obj/item/clothing/gloves.dm
  code/obj/item/deployable_turret.dm
  code/obj/item/gun/gun_parent.dm
  code/obj/item/gun/kinetic.dm
  code/obj/item/implant.dm
  code/obj/storage/crates.dm
  code/procs/scanprocs.dm
  icons/obj/deployableturret.dmi
  icons/obj/projectiles.dmi
Labels: size/XL

#496 Armory Mercantile Services (Warware) turret for someday
  code/atom/throwing.dm
  code/modules/projectiles/bullet.dm
  code/obj/item/deployable_turret.dm
  icons/effects/lines2.dmi
Labels: size/M

#487 Makes chemical cans able to be wrenched open/closed + closedcontainer changes
  code/modules/chemistry/Chemistry-Tools.dm
  code/modules/chemistry/tools/food_and_drink.dm
  code/modules/chemistry/tools/fuel_tanks.dm
  icons/obj/objects.dmi
Labels: size/S

#497 Pitfalls again! WIP Sinkhole, safety/sanity checks, and landing on stuff.
  code/datums/components/pitfall.dm
  code/mob/dead.dm
  code/modules/events/minor/sinkhole.dm
  code/modules/gunse/gun_persistence.dm
  code/modules/shuttles/transit_vehicle.dm
  code/obj/item/grab.dm
  code/obj/item/instruments.dm
  code/obj/landmark.dm
  code/obj/table.dm
  coolstation.dme
Labels: size/L

#500 Make the game compile faster by removing a ton of NSS Bootlick- I mean NSS Manta shit
  .github/workflows/automaton.yml
  _std/__build.dm
  _std/defines/atom.dm
  _std/defines/landmarks.dm
  _std/defines/shuttle.dm
  _std/defines/turf.dm
  _std/mapDefines.dm
  code/WorkInProgress/Particles.dm
  code/WorkInProgress/mantaObjects.dm
  code/WorkInProgress/missile_latejoin.dm
  code/WorkInProgress/torpedoes.dm
  code/area.dm
  code/atom.dm
  code/datums/controllers/process/forcedMovement.dm
  code/datums/jobs.dm
  code/datums/miscreant_objectives.dm
  code/datums/objective.dm
  code/datums/prefab_shuttles.dm
  code/map.dm
  code/mob/dead.dm
  code/mob/dead/observer.dm
  code/mob/living/intangible.dm
  code/mob/living/seanceghost.dm
  code/mob/wraith.dm
  code/mob/zoldorfmob.dm
  code/modules/_unused/dialogue_NTcommander.dm
  code/modules/economy/trader.dm
  code/modules/events/minor/pests.dm
  code/modules/fluids/fluid_commands.dm
  code/modules/fluids/fluid_core.dm
  code/modules/fluids/fluid_objects.dm
  code/modules/fluids/fluid_turf.dm
  code/modules/transport/pods/vehicle.dm
  code/modules/worldgen/prefabs.dm
  code/obj.dm
  code/obj/critter/drone.dm
  code/obj/decal/poster.dm
  code/obj/item/paper.dm
  code/obj/item/tank.dm
  code/obj/landmark.dm
  code/obj/machinery/door/door_control.dm
  code/obj/machinery/nuclearbomb.dm
  code/obj/machinery/shipalert.dm
  code/obj/storage/closets.dm
  code/world.dm
  maps/config/map.dm
Labels: size/XXL

#505 Fixes dark purpleblack tiles using light purple corners
  icons/turf/floors.dmi
Labels: size/XS

#504 Pizza rework!
  _std/macros/movable.dm
  code/atom/UpdateOverlays.dm
  code/datums/cookingrecipes.dm
  code/datums/crew_objective.dm
  code/mob/living/critter/bee.dm
  code/modules/atmospherics/machinery/unary/cryo_cell.dm
  code/modules/chemistry/Reagents-Misc.dm
  code/modules/food_and_drink/ingredients.dm
  code/modules/food_and_drink/pizza.dm
  code/modules/food_and_drink/snacks.dm
  code/modules/medical/surgery_tools.dm
  code/modules/vending/vending.dm
  code/obj/critter/bee.dm
  code/obj/item/kitchen.dm
  code/obj/random_spawners.dm
  coolstation.dme
  icons/obj/Cryogenic2.dmi
  icons/obj/foodNdrink/food_bread.dmi
  icons/obj/foodNdrink/food_ingredient.dmi
  icons/obj/foodNdrink/food_meals.dmi
  maps/z2.dmm
  maps/z3.dmm
Labels: size/XXL

#502 Pcui jumplist
  _std/defines/pcui.dm
  code/chui/pcui/templates/manufacturer-template.dm
  code/chui/pcui/templates/selector-template.dm
  code/chui/pcui/templates/template-datum.dm
  code/chui/window.dm
  code/datums/gamemodes/battle_royale.dm
  code/global.dm
  code/modules/admin/admin.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/adminjump.dm
  code/world.dm
  coolstation.dme
  strings/admin_changelog.txt
Labels: size/XL

#503 Legibility pass on bitflags
  _std/defines/actions.dm
  _std/defines/admin.dm
  _std/defines/atom.dm
  _std/defines/clothing.dm
  _std/defines/combat.dm
  _std/defines/computer.dm
  _std/defines/construction.dm
  _std/defines/dmm_suite.dm
  _std/defines/mob.dm
  _std/vox.dm
  code/WorkInProgress/griffening/griffening_cards.dm
  code/WorkInProgress/telescope/telescopeEvents.dm
  code/datums/browserOutput.dm
  code/datums/controllers/sea_hotspot_controls.dm
  code/datums/gauntlet/podcolosseum.dm
  code/modules/fluids/fluid_turf.dm
  code/modules/networks/computer3/mainframe2/_base_os.dm
Labels: size/L

#498 minor deep fryer bug fix
  code/obj/machinery/deep_fryer.dm
Labels: size/XS

#507 Mobs that die with no mind are no longer checked for objectives/medals etc.
  code/mob/living/carbon/human.dm
Labels: size/M

#506 everything but tgui onto 516 spec, i think
  browserassets/css/chui/chui.css
  browserassets/css/chui/flockdrone.css
  browserassets/css/chui/themes/default/default.css
  browserassets/css/tooltip.css
  browserassets/html/admin/banPanel.html
  browserassets/html/admin/color_matrix.html
  browserassets/html/materialRecombobulator.html
  browserassets/html/tooltip.html
  browserassets/js/browserOutput.js
  browserassets/js/chemicompiler.js
  browserassets/js/chui/chui-old.js
  browserassets/js/chui/chui.js
  browserassets/js/clothingbooth.js
  browserassets/js/errorHandler.js
  browserassets/js/flockmind.js
  browserassets/js/go.js
  browserassets/js/interfaceSizeHelper.js
  browserassets/js/pathoui-script.js
  browserassets/js/processScheduler.js
  browserassets/js/runtimeViewer.js
  browserassets/js/telescope.js
  browserassets/js/tooltip.js
  browserassets/js/zoldorf.js
  code/WorkInProgress/SpoogemonstersStuff.dm
  code/chui/pcui/templates/manufacturer-template.dm
  code/datums/controllers/event_controls.dm
  code/datums/tooltip.dm
  code/mapSwitching.dm
  code/mob/living/silicon/ai.dm
  code/modules/admin/loginnotice.dm
  code/modules/admin/player_panel.dm
  code/modules/admin/randomverbs.dm
  code/modules/atmospherics/machinery/binary/pump_ui.dm
  code/modules/materials/Mat_Fabrication.dm
  code/modules/power/nuke/nuke.dm
  code/modules/power/reactor_stats.dm
  code/modules/robotics/bot/mining.dm
  code/modules/transport/pods/secondary_system.dm
  code/obj/item/storage/secure_safe.dm
  code/obj/machinery/computer/QM_supply.dm
  code/obj/machinery/computer/pod.dm
  code/obj/machinery/computer/secure_data.dm
  code/obj/machinery/computer/tetris/tetris.dm
  code/obj/machinery/singularity.dm
  code/obj/submachine/cooking.dm
  code/procs/helpers.dm
  code/procs/station_name.dm
  code/z_adventurezones/meatland.dm
Labels: size/L

#509 PR that makes the active hilight old
  browserassets/css/chui/themes/default/default.css
Labels: size/XS

#510 Fix the text stroke on the join screen
  code/datums/titlecard.dm
Labels: size/XS

#511 Native custom scrollbar css
  browserassets/css/chui/themes/default/default.css
Labels: size/S

#508 Adjust the job colors to meet contrast standards
  code/datums/jobs.dm
Labels: size/M

#516 Native scrollbars and minor margin tweak
  browserassets/css/chui/themes/default/default.css
  code/chui/theme.dm
  code/mob/new_player.dm
Labels: size/M

#518 Crag-time
  _std/__build.dm
Labels: size/XS

#519 Revert "Native scrollbars and minor margin tweak"
  browserassets/css/chui/themes/default/default.css
  code/chui/theme.dm
  code/mob/new_player.dm
Labels: size/M

#520 bugfixes and webview devtool granting
  code/datums/components/pitfall.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/debug.dm
Labels: size/S

#522 Cancel button dosen't activate jump form
  code/chui/pcui/templates/selector-template.dm
Labels: size/XS

#521 Local servers use absolute file names for browser resources
  browserassets/css/tgui/all.min.css
  code/modules/localassets/localassets_tgui.dm
  code/procs/resourceManagement.dm
Labels: size/M

#526 spawn windows don't share the same name
  code/chui/pcui/templates/selector-template.dm
Labels: size/XS

#527 Auto closing airbridges - New old airbridge appearances
  code/obj/airbridge.dm
  code/obj/machinery/door/door_parent.dm
  code/turf/turf_drawbridge.dm
Labels: size/L

#529 Makes ferns check for monke and quiet the sounds accordingly
  code/obj/decorations.dm
Labels: size/S

#523 bigger pizzas for bigger toppings
  code/modules/food_and_drink/ingredients.dm
  code/modules/food_and_drink/pizza.dm
Labels: size/M

#530 Adds inner elevator corner iconstates.
  icons/turf/floors.dmi
Labels: size/XS

#528 Blobby
  code/datums/abilities/ability_parent.dm
  code/datums/gamemodes/blob.dm
  code/datums/objective.dm
  code/mob/living/intangible/blob_overmind.dm
  code/mob/living/intangible/blob_overmind/ai.dm
  code/modules/admin/admin.dm
  code/modules/antagonists/blob/blob_abilities.dm
  code/modules/chemistry/Reagents-PoisonEtc.dm
  code/modules/tutorials/blob_tutorial.dm
  code/obj/blob.dm
  code/procs/helpers.dm
  code/turf/floors.dm
  strings/admin_changelog.txt
Labels: size/XXL

#531 Crag Refresh: Part 1
  maps/warwip/the_crag.dmm
  maps/warwip/z3_the_crag.dmm
Labels: size/XXL

#534 Moves CDN to HTTPS
  _std/__build.dm
  browserassets/Gruntfile.js
  browserassets/js/browserOutput.js
  browserassets/js/chui/chui.js
  browserassets/tgui/tgui.html
  config/config.txt
Labels: size/S

#535 Makes Gehennan paths visible in StrongDMM again
  code/WorkInProgress/gehenna.dm
Labels: size/S

#536 Remove non-engine airless tiles from crag z3
  maps/warwip/z3_the_crag.dmm
Labels: size/M

#537 Alters FEA spacing to check for ACTUAL space.
  code/WorkInProgress/gehenna.dm
  code/modules/atmospherics/FEA_system.dm
  code/modules/atmospherics/FEA_turf_tile.dm
Labels: size/S

#524 Landing gear imprints and path edges (DO NOT PLACE IN MAPS YET)
  code/WorkInProgress/gehenna.dm
  code/obj/decal.dm
  icons/effects/64x64.dmi
  icons/turf/gehenna_overlays.dmi
Labels: size/M

#540 Fix the TGUI Knob and Number Input, and fix the CHUI CORS error.
  browserassets/js/chui/chui.js
  browserassets/tgui/tgui-panel.bundle.js
  browserassets/tgui/tgui.bundle.js
  code/modules/interface/keybind_menu_chui.dm
  code/obj/machinery/phone.dm
  config/config.txt
  tgui/packages/tgui/components/DraggableControl.js
  tgui/packages/tgui/components/NumberInput.js
Labels: size/S

#538 Scorpion sight
  code/datums/components/blacklight_visible.dm
  code/mob/living/critter/small_animal.dm
  coolstation.dme
Labels: size/M

#541 fuckin OOPS
  config/config.txt
Labels: size/XS

#543 Crag changes: Part 2
  code/obj/decal/poster.dm
  code/procs/scanprocs.dm
  code/turf/floors.dm
  icons/obj/decals/posters_64x32.dmi
  icons/turf/floors.dmi
  maps/warwip/the_crag.dmm
  maps/warwip/z3_the_crag.dmm
Labels: size/XXL

#539 Updrafts, like a pitfall but backwards.
  _std/defines/atom.dm
  code/WorkInProgress/AnimationLibrary.dm
  code/datums/components/pitfall.dm
  code/datums/components/updraft.dm
  code/modules/chemistry/Reagents-Base.dm
  code/modules/chemistry/tools/balloons.dm
  code/modules/fluids/air.dm
  code/modules/shuttles/transit_vehicle.dm
  code/obj/effects/bad_smoke.dm
  code/obj/effects/harmless_smoke.dm
  code/procs/fireflash.dm
  code/procs/gamehelpers.dm
  coolstation.dme
Labels: size/L

#542 elevator shaft emergency lighting
  code/modules/shuttles/transit_vehicle.dm
  code/obj/machinery/shipalert.dm
  icons/obj/pathlights.dmi
Labels: size/L, merge conflict

#545 Tangerine floors
  code/turf/floors.dm
  icons/turf/floors.dmi
Labels: size/M

#548 Unify throwing code
  code/mob/living.dm
  code/mob/living/carbon/human.dm
  code/mob/living/critter.dm
Labels: size/L

#544 system for deferred world gen (that isn't spawn_dbg)
  code/atom.dm
  code/datums/gameticker.dm
  code/modules/fluids/fluid_turf.dm
  code/modules/worldgen/worldgen_parent.dm
  code/obj/grille.dm
  code/obj/mining.dm
  code/obj/window.dm
  code/turf/turf.dm
  code/turf/turf_autoalign.dm
  code/z_dmm_suite/reader.dm
Labels: size/L

#549 Allow critters to slidekick
  code/mob/living.dm
  code/mob/living/carbon/human.dm
Labels: size/L

#550 Neutral greys the recordtrak, adds N.A.R.C.O. scanners
  code/obj/item/device/scanners.dm
  icons/obj/items/device.dmi
  maps/warwip/z3_the_crag.dmm
Labels: size/M

#551 A tasteful application of anti-drug posters and telephones to Crag
  code/obj/decal/poster.dm
  icons/obj/decals/posters.dmi
  maps/warwip/the_crag.dmm
  maps/warwip/z3_the_crag.dmm
Labels: size/L

#552 Removes some airless tiles from the fossie outpost, adds some airless tiles to the engine exhaust
  maps/warwip/the_crag.dmm
Labels: size/L

#553 Resprites N.A.R.C.O and several other sec tools to have the same design language and colors
  icons/obj/items/device.dmi
Labels: size/XS

#556 Fireflashes from combustion heat air
  code/procs/fireflash.dm
Labels: size/XS

#557 Second iteration of chemical combustion heating atmos
  code/modules/chemistry/Chemistry-Holder.dm
  code/modules/chemistry/Chemistry-Reagents.dm
  code/modules/chemistry/Reagents-Base.dm
  code/modules/chemistry/Reagents-ExplosiveFire.dm
  code/modules/chemistry/Reagents-FoodDrink.dm
  code/modules/chemistry/Reagents-Medical.dm
  code/modules/chemistry/Reagents-Misc.dm
  code/procs/fireflash.dm
Labels: size/L

#558 fix vr nullspace
  code/mob/living/carbon/human/virtual.dm
Labels: size/XS
